### ISSUE TITLE
Refactor models inside bike map app

### ISSUE THREAD

**Issue by AntoniPokrzywa** [AntoniPokrzywa/Sociale#20]
# TODO
- [ ] Find way to return bike code on bike_get, the encryption and decryption on frontend? Is it needed when using HTTPS? 
- [ ] Bike codes should be stored somehow securelly if db gets leaked, the django crypto plugin is outdated and not supported
- [ ] The methods on rentals should be moved to services, 'clean' should be added 
- [ ] Parking should remain method 'contains' - which should be improved, also 'clean' should be implemented

**Comment by AntoniPokrzywa** [comment]
To task nr.1 , code will be stored on DB encrypted, i will encrypt and decrypt it on app, then send it directly to frontend as api key or so. It's not cryptography project ....
